#!/bin/bash 

#Reference Wiki : https://github.com/Ch00k/openstack-install-aio/blob/master/openstack-all-in-one.rst#operating-system

. functions
   
#Neutron: server& pluggins
function neutron {
   apt-get install -y neutron-server neutron-plugin-openvswitch neutron-plugin-openvswitch-agent dnsmasq neutron-dhcp-agent neutron-l3-agent neutron-metadata-agent
   service neutron-server stop
   modify_neutron_conf
   rm /var/lib/neutron/neutron.sqlite
   for i in $( ls /etc/init.d/neutron-* ); do service `basename $i` restart; done
   service dnsmasq restart
}

#Nova
function nova {
   apt-get install -y nova-api nova-cert novnc nova-consoleauth nova-scheduler nova-novncproxy nova-doc nova-conductor nova-compute-kvm
   modify_nova_conf 
   for i in $( ls /etc/init.d/nova-* ); do service `basename $i` restart; done
   rm /var/lib/nova/nova.sqlite
   nova-manage db sync
   for i in $( ls /etc/init.d/nova-* ); do service `basename $i` restart; done
}

#Cinder
function cinder {
   apt-get install -y cinder-api cinder-scheduler cinder-volume
   pvcreate $CINDER_PART
   vgcreate cinder-volumes $CINDER_PART
   modify_cinder_conf 
   rm /var/lib/cinder/cinder.sqlite
   cinder-manage db sync
   service tgt restart
   for i in $( ls /etc/init.d/cinder-* ); do service `basename $i` restart; done
}

#Swift
function swift {
   apt-get -y install swift swift-account swift-container swift-object swift-proxy openssh-server memcached python-pip python-netifaces python-xattr python-memcache xfsprogs python-keystoneclient python-swiftclient python-webob git
   modify_swift_conf
}

#Horizon
function horizon  {
   apt-get -y install openstack-dashboard memcached && dpkg --purge openstack-dashboard-ubuntu-theme
   modify_horizon_conf
   service apache2 restart; service memcached restart
}

function install_completed {
   echo "****************************************************************************************"
   echo "* Installation of openstack components all in one node is completed........            *"
   echo "* Now run test_install to setup neutron networks, subnets and routers for  the VMs     *"
   echo "* After which you can access openstack from http://<externel ip>/horizon/              *"
   echo "****************************************************************************************"
}

#Execution begins here
function all {
   neutron
   nova
   cinder
   swift
   horizon
   install_completed
}

function help {
  echo Usage
  echo "./install_part2 <option> where option can be one of the below"
  echo update
  echo mysql
  echo keystone
  echo glance
  echo ovs 
  echo all
}

readonly user=`whoami`
if [ "X$user" != "Xroot" ]; then
   echo "You should be a root user to run this script"
   exit
fi

if [ "X$1" == "X" ]; then
   help
   exit
fi

ROOT_DIR=`pwd`
read -p "Enter the External IP " EXT_IP
read -p "Enter the Internal IP " MGMT_IP
read -p "Enter the swift partition (format: sdaX)" SWIFT_PART
read -p "Enter the cinder partition (format: /dev/sdaX)" CINDER_PART
read -p "Enter the OS password " OPENSTACK_PW
   
$1
rc=`echo $?`
if [ $rc == 127 ]; then
   help
fi
