#!/bin/bash -x

   read -p "Enter the Floating IP start address" FIP_START
   read -p "Enter the Floating IP end address" FIP_END
   read -p "Enter the Floating IP Subnet in CIDR format(e.g 10.0.0.0/24)" FIP_SUBNET

   neutron net-create testnetwork
   neutron subnet-create --name testsubnet testnetwork 10.0.0.0/24
   testsubnet=`neutron subnet-list | grep testsubnet | awk -F "|" '{print $2}'`
   neutron subnet-update $testsubnet --dns_nameservers list=true 8.8.8.8
 
   neutron router-create testrouter
   router=`neutron router-list | grep testrouter | awk -F "|" '{print $2}'`
   neutron router-interface-add $router $testsubnet
   
   neutron net-create ext_net --router:external=True
   extnet=`neutron net-list | grep ext_net | awk -F "|" '{print $2}'`
   neutron subnet-create --name extsubnet --allocation-pool start=$FIP_START,end=$FIP_END ext_net $FIP_SUBNET --enable_dhcp=False
   neutron router-gateway-set $router $extnet 
   
   nova secgroup-add-rule default icmp -1 -1 0.0.0.0/0
   nova secgroup-add-rule default tcp 1 65535 0.0.0.0/0
   nova secgroup-add-rule default udp 1 65535 0.0.0.0/0
